### ISSUE TITLE
Failed to build extension code with "shopify extension push"

### ISSUE THREAD

**Issue by chenster** [Shopify/product-reviews-sample-app#14]
`shopify extension push` returns the following

```
Failed to build extension code.
┏━━ Building extension with: npm… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃
┃ > product-reviews-sample-checkout-extension@0.1.0 build
┃ > checkout-ui-extensions-run build
┃
┃ sh: checkout-ui-extensions-run: command not found
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```
What's funny is that it did create checkout extension albeit the error.

**Comment by ScottJr** [comment]
For the add section or add block in the theme editor, on development stores, in the extension settings I had to set `DEVELOPMENT STORE PREVIEW` to enabled in order for it to show on my theme (Dawn)

**Comment by tommy921092** [comment]
> I found this from the [Theme app extensions overview docs](https://shopify.dev/apps/online-store/theme-app-extensions) helpful
> 
> > Theme app extensions are currently available in a developer preview and can only be used in development stores.
> 
> For the add section or add block in the theme editor, on development stores, in the extension settings I had to set `DEVELOPMENT STORE PREVIEW` to enabled in order for it to show on my theme (Dawn)

I had my DEVELOPMENT STORE PREVIEW enabled but still its not showing on my theme. Any ideas?
