### ISSUE TITLE
deprecated metafield type "json_string" vs. new "json"

### ISSUE THREAD

**Issue by lfritsche** [Shopify/product-reviews-sample-app#2]
Based on the current docs https://shopify.dev/api/liquid/objects/metafield#deprecated-metafields I wondered why this sample app is using the deprecated `json_string`.
https://github.com/Shopify/product-reviews-sample-app/blob/ab5e5f09e76d83b950e02f4ae8b649455a0a694c/server/handlers/mutations/add-review.js#L36

Could this be because the 2019-10 API version only supports the old types?
https://github.com/Shopify/product-reviews-sample-app/blob/ab5e5f09e76d83b950e02f4ae8b649455a0a694c/server/handlers/client.js#L5

Can I use the new `json` type the same way `json_string` is used in this example?

Thanks!

**Comment by stevemar** [comment]
This issue was addressed in #61
