### ISSUE TITLE
Update app to work with Node v17+

### ISSUE THREAD

**Issue by stevemar** [Shopify/product-reviews-sample-app#32]
Trying to run this application using `shopify app serve` generates a warning if you're running with Node v17 or newer. See [related issue](https://github.com/Shopify/shopify-cli/issues/1808).

```
┃ Error: Package subpath './lib/parser' is not defined by "exports" in /Users/stevemartinelli/src/github.com/Shopify/product-reviews-sample-app/node_modules/next/node_modules/postcss/package.json
…
(/Users/stevemartinelli/src/github.com/Shopify/product-reviews-sample-app/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:3733) {
┃   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
┃ }
┃ 
┃ Node.js v17.5.0
┃ [nodemon] app crashed - waiting for file changes before starting...
```

While we evaluate the work required to update to the latest Shopify Node library we should do at least the following:
* Document what version of Node works 
* Use a [.node_version](https://stackoverflow.com/questions/27425852/what-uses-respects-the-node-version-file) file in the repo which is often honored by tools such as `nvm`

**Comment by eyal9** [comment]
i have the same error, what do i do exactly? pls help
