### ISSUE TITLE
How to use modules?

### ISSUE THREAD

**Issue by TheApeMachine** [Shopify/product-reviews-sample-app#45]
### Issue

Hi,

So I am migrating our old app, which used the ScriptTag API to inject itself into the page and had a Laravel backend to use the new Theme App Extensions, using NextJS.

We were making use of Javascript modules  to keep the Javascript ordered and composable, but I am not entirely clear on how to so this with Theme App Extensions. I suppose I could somehow pre-build the final JS file, like the Laravel version used to do with Mix, but is there some standard way this should be working?

**Comment by meganmajewski** [comment]
Hi @TheApeMachine 
This question is not directly related to the sample application in this repo, but I'm happy to provide some general direction.
We currently do not have a set standard for using modular JS in Theme App Extensions
We do have standards for how to build your [Theme App Extensions](https://shopify.dev/apps/online-store/theme-app-extensions/extensions-framework) and a [UX guide](https://shopify.dev/apps/online-store/theme-app-extensions/ux-guidelines) for theme apps.

At this time your question is better posted in the [Slack](https://join.slack.com/t/shopifypartners/shared_invite/zt-sdr2quab-mGkzkttZ2hnVm0~8noSyvw), [Discord](https://discord.com/invite/shopifydevs), or [Community Forums](https://community.shopify.com/c/shopify-community/ct-p/en) where people might have recommendations for you.

**Comment by TheApeMachine** [comment]
k, I temporarily "solved" it as such.
```
node ..\..\node_modules\webpack\bin\webpack.js ./.\co2okButton.js --output-filename=climate-neutral-checkout.js --mode=development ; rm climate-neutral-checkout.js ; mv .\dist\climate-neutral-checkout.js . ; cd ../ ; shopify extension push ; cd assets
```
Now if only this push would not fail half of the time this could almost be considered a workflow :p
