### ISSUE TITLE
why /apps/prapp/reviews path ? 

### ISSUE THREAD

**Issue by TanguyDH** [Shopify/product-reviews-sample-app#5]
https://github.com/Shopify/product-reviews-sample-app/blob/ab5e5f09e76d83b950e02f4ae8b649455a0a694c/theme-app-extension/assets/product-reviews-form.js#L26

**Comment by tommy921092** [comment]
As far as I know this act as app proxy such that the user cannot directly call your api backend routes for better security.
so its actually calling /api/reviews in your backend. apps as prefix and prapp as subpath as mentioned in DOC.

**Comment by TrevPennington** [comment]
what / where is the file that handles this request?

**Comment by stevemar** [comment]
This example uses an app-proxy to ensure a user cannot call the API directly. This is, as @tommy921092 pointed out, for improved security. There's plenty of info about [app proxies on shopify.dev](https://shopify.dev/apps/online-store/app-proxies)

The way it works in this repository is the theme extension calls out to the proxy `/apps/prapp/reviews`:

https://github.com/Shopify/product-reviews-sample-app/blob/435ebf4b1b2d30c0372f11c42a41ae4ad5c96b10/theme-app-extension/assets/product-reviews-form.js#L26

And the main application serves the API `/api/reviews`

https://github.com/Shopify/product-reviews-sample-app/blob/435ebf4b1b2d30c0372f11c42a41ae4ad5c96b10/server/server.js#L217-L224

The documentation calls out that if you're using this example you should be adding a `/apps/prapp` app proxy (see Step 7). So, effectively, calls to `/apps/prapp/reviews` are going to `/api/reviews`

https://github.com/Shopify/product-reviews-sample-app/blob/main/docs/getting-started.md#7-set-up-the-app-proxy-extension

Hope this clears things up!
