### ISSUE TITLE
Unknown extension type THEME_APP_EXTENSION

### ISSUE THREAD

**Issue by StandMind** [Shopify/product-reviews-sample-app#6]
I follow the steps of 'Register the Theme app extension to your app' in 'getting-started.md'.PowerShell shows 'Unknown extension type THEME_APP_EXTENSION'

**Comment by StandMind** [comment]
the command is 'shopify extension register'

**Comment by Teetomania** [comment]
I started afresh with 'shopify extension create' and copied the files in the existing theme folder into the new folder. It worked for me. I also defered the product-reviews-form.js like this <script src="{{ 'product-reviews-form.js' | asset_url }}" defer></script> to solve the next error.

**Comment by StandMind** [comment]
> I started afresh with 'shopify extension create' and copied the files in the existing theme folder into the new folder. It worked for me. I also defered the product-reviews-form.js like this <script src="{{ 'product-reviews-form.js' | asset_url }}" defer></script> to solve the next error.

Thank you for your solution!!!!It worked!!!!! 💯 :D
