### ISSUE TITLE
Error "The script_tag filter is parser-blocking..." when running "shopify extension push"

### ISSUE THREAD

**Issue by ratapof** [Shopify/product-reviews-sample-app#7]
Hello, i have followed the getting started guide precisely, but i am getting an error when trying to[ push the shopify app extension](https://github.com/Shopify/product-reviews-sample-app/blob/main/docs/getting-started.md#register-the-theme-app-extension-to-your-app).

The whole error is:
`X The script_tag filter is parser-blocking. Use a script tag with the async or defer attribute for better performance at blocks/product-reviews.liquid:46`

Which happens after runing "shopify extension push", after having followed [the guide](https://github.com/Shopify/product-reviews-sample-app/blob/main/docs/getting-started.md#getting-started).

The error prevents the app extension from being pushed.

**Comment by ratapof** [comment]
fixed by replacing line 46 in theme-app-extension/blocks/product-reviews.liquid with:
`<script src="{{ 'product-reviews-form.js' | asset_url }}" defer></script>`

**Comment by carlzoo** [comment]
It's weird that Shopify's own example would be rejected by their own parser, this would confuse people trying to learn.

https://github.com/Shopify/product-reviews-sample-app/pull/9

**Comment by ltakens** [comment]
+1

**Comment by tommy921092** [comment]
I couldn't run the app after app the setup done, it just redirect to a blank page without any error, anyone the same?

**Comment by tommy921092** [comment]
> It's weird that Shopify's own example would be rejected by their own parser, this would confuse people trying to learn.
> 
> #9

Shopify always expect us to fix their sample app and libraries to solve those issue.

**Comment by daviareias** [comment]
At least I'm happy that shopify does something to make sure apps won't slow down stores.
